all:
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main.exe main.c
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main-kadane.exe main-kadane.c
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main-cuadratic.exe main-cuadratic.c

clean:
	rm -rf *.exe *.dSYM *~
