all:
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main main.c
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main-kadane main-kadane.c
#	gcc -g -o main main.c

clean:
	rm -rf main *~
