all:
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main-max-sum.exe main-max-sum.c
	gcc -lm -O2 -pipe -std=c90 -pedantic -DONLINE_JUDGE -o main-kadane.exe main-kadane.c

clean:
	rm -rf *.exe *.dSYM *~
